<Project>
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RestoreIgnoreFailedSources>true</RestoreIgnoreFailedSources>
    <RestoreConfigFile>$(MSBuildThisFileDirectory)NuGet.Config</RestoreConfigFile>
    <BaseOutputPath Condition="'$(GitlandBuildRoot)' != ''">$(GitlandBuildRoot)/$(MSBuildProjectName)/</BaseOutputPath>
  </PropertyGroup>
</Project>
